### PR TITLE
Add variable debug support.

### PR DESCRIPTION
**Pull request by clemens-tolboom**
To find out what variables are used this new target can be used like

```
make print-USER_ID
make print-GROUP_ID
```

or even better

```
make env
```

resulting in (MacOS)

> TZ = America/Sao_Paulo
USER_ID = 501
GROUP_ID = 1000

### CODE REVIEW

**Comment by lucasconstantino** [comment]
First of all, thank you so much for contributing! In which situations did you need use these commands? Why was it important to you, in the first place?

Could you also clarify why are you are contributing to this project?

@sebas5384 care to have a look?

**Comment by clemens-tolboom** [comment]
I did want to know what settings where used esp. for GROUP_ID so figured why not add this for bug reporting for others. Furthermore the TZ was puzzling me a little.

With this PR we can all enjoy this setting debugging 👍

**Comment by clemens-tolboom** [comment]
To answer

> Could you also clarify why are you are contributing to this project?

@sebas5384 told us about this project in https://drupal.slack.com/archives/C6LMJ0ZAT/p1525812800000571

**Comment by lucasconstantino** [comment]
I see value on clarifying this environment variables, ok. But really I think we should improve this docker configuration, simplify it, and maybe even get rid of these variables completely. This Dockerfile/Makefile were build based on real projects we have, they have lots of disposable code really.

**Comment by clemens-tolboom** [comment]
@Leocardoso94 agreed there are several issues with project regarding Docker/Makefile. Feel free to close.

**Pull request closed without merging**
